### PR TITLE
Fix off-by-one error in message reporting network value range

### LINKED ISSUE #1545: in networkX, when passing net value at maximum, returns an off-by-one error message.
> wwiv@wwivdeb:~$ network1 --net=2
2023-01-27 16:03:20,096 ERROR network number must be between 0 and 2.
network1 [5.8.0.development]

### PR DESCRIPTION
**Pull request by ericpareja**
Fix #1545

### CODE REVIEW

File: net_core/net_cmdline.cpp [hunk 1]
```diff
@@ -87,7 +87,7 @@ NetworkCommandLine::NetworkCommandLine(wwiv::core::CommandLine& cmdline, char ne
   const auto& nws = networks_->networks();
 
   if (network_number_ < 0 || network_number_ >= size_int(nws)) {
```
Comment (wwiv) [inline net_core/net_cmdline.cpp:95]: this fails for 0 networks, maybe add another if before this to say "no networks defined" or somethibg?

**Review by wwiv — APPROVED** [review]

**Review by wwiv — APPROVED** [review]
